package Modelos;
// Generated 10-jun-2019 1:48:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categorias generated by hbm2java
 */
public class Categorias  implements java.io.Serializable {


     private Integer idcategorias;
     private String nombre;
     private Set productoses = new HashSet(0);

    public Categorias() {
    }
    
     public Categorias(String nombre) {
       this.nombre = nombre;
       
    }

    public Categorias(String nombre, Set productoses) {
       this.nombre = nombre;
       this.productoses = productoses;
    }
   
    public Integer getIdcategorias() {
        return this.idcategorias;
    }
    
    public void setIdcategorias(Integer idcategorias) {
        this.idcategorias = idcategorias;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }




}


