package Modelos;
// Generated 10-jun-2019 1:48:46 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compras generated by hbm2java
 */
public class Compras  implements java.io.Serializable {


     private Integer idcompras;
     private Proveedores proveedores;
     private String referencia;
     private Long importe;
     private Date createTime;
     private Set tienes = new HashSet(0);

    public Compras() {
    }

	
    public Compras(Proveedores proveedores, String referencia) {
        this.proveedores = proveedores;
        this.referencia = referencia;
    }
    public Compras(Proveedores proveedores, String referencia, Long importe, Date createTime, Set tienes) {
       this.proveedores = proveedores;
       this.referencia = referencia;
       this.importe = importe;
       this.createTime = createTime;
       this.tienes = tienes;
    }
     public Compras(Proveedores proveedores, String referencia, Long importe, Date createTime) {
       this.proveedores = proveedores;
       this.referencia = referencia;
       this.importe = importe;
       this.createTime = createTime;
       
    }
   
    public Integer getIdcompras() {
        return this.idcompras;
    }
    
    public void setIdcompras(Integer idcompras) {
        this.idcompras = idcompras;
    }
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public Long getImporte() {
        return this.importe;
    }
    
    public void setImporte(Long importe) {
        this.importe = importe;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Set getTienes() {
        return this.tienes;
    }
    
    public void setTienes(Set tienes) {
        this.tienes = tienes;
    }




}


