package Modelos;
// Generated 10-jun-2019 1:48:46 by Hibernate Tools 4.3.1



/**
 * Contiene generated by hbm2java
 */
public class Contiene  implements java.io.Serializable {


     private ContieneId id;
     private Productos productos;
     private Ventas ventas;
     private int cantidad;

     public Contiene() {
    }

    public Contiene(ContieneId id, Productos productos, Ventas ventas, int cantidad) {
       this.id = id;
       this.productos = productos;
       this.ventas = ventas;
       this.cantidad = cantidad;
    }
   
    public ContieneId getId() {
        return this.id;
    }
    
    public void setId(ContieneId id) {
        this.id = id;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public Ventas getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Ventas ventas) {
        this.ventas = ventas;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


