package Modelos;
// Generated 10-jun-2019 1:48:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer idproductos;
     private Categorias categorias;
     private Proveedores proveedores;
     private String referencia;
     private String descripcion;
     private Long precioCompra;
     private Long precioVenta;
     private Integer cantidad;
     private Set contienes = new HashSet(0);
     private Set tienes = new HashSet(0);

     public Productos() {
    }

	
    public Productos(Categorias categorias, Proveedores proveedores) {
        this.categorias = categorias;
        this.proveedores = proveedores;
    }
    public Productos(Categorias categorias, Proveedores proveedores, String referencia, String descripcion, Long precioCompra, Long precioVenta, Integer cantidad) {
       this.categorias = categorias;
       this.proveedores = proveedores;
       this.referencia = referencia;
       this.descripcion = descripcion;
       this.precioCompra = precioCompra;
       this.precioVenta = precioVenta;
       this.cantidad = cantidad;
    }
   
    public Integer getIdproductos() {
        return this.idproductos;
    }
    
    public void setIdproductos(Integer idproductos) {
        this.idproductos = idproductos;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Long getPrecioCompra() {
        return this.precioCompra;
    }
    
    public void setPrecioCompra(Long precioCompra) {
        this.precioCompra = precioCompra;
    }
    public Long getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(Long precioVenta) {
        this.precioVenta = precioVenta;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Set getContienes() {
        return this.contienes;
    }
    
    public void setContienes(Set contienes) {
        this.contienes = contienes;
    }
    public Set getTienes() {
        return this.tienes;
    }
    
    public void setTienes(Set tienes) {
        this.tienes = tienes;
    }




}


