package Modelos;
// Generated 10-jun-2019 1:48:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedores generated by hbm2java
 */
public class Proveedores  implements java.io.Serializable {


     private Integer idproveedores;
     private String nombre;
     private String direccion;
     private String identificacion;
     private String poblacion;
     private Integer codPostal;
     private Integer telefono;
     private String email;
     private Set productoses = new HashSet(0);
     private Set comprases = new HashSet(0);

    public Proveedores() {
    }

    public Proveedores(String nombre, String direccion, String identificacion, String poblacion, Integer codPostal, Integer telefono, String email) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.identificacion = identificacion;
       this.poblacion = poblacion;
       this.codPostal = codPostal;
       this.telefono = telefono;
       this.email = email;
       
    }
   
    public Integer getIdproveedores() {
        return this.idproveedores;
    }
    
    public void setIdproveedores(Integer idproveedores) {
        this.idproveedores = idproveedores;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }
    public String getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }
    public Integer getCodPostal() {
        return this.codPostal;
    }
    
    public void setCodPostal(Integer codPostal) {
        this.codPostal = codPostal;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }
    public Set getComprases() {
        return this.comprases;
    }
    
    public void setComprases(Set comprases) {
        this.comprases = comprases;
    }




}


