package Modelos;
// Generated 10-jun-2019 1:48:46 by Hibernate Tools 4.3.1



/**
 * TieneId generated by hbm2java
 */
public class TieneId  implements java.io.Serializable {


     private int idcompras;
     private int idproductos;

    public TieneId() {
    }

    public TieneId(int idcompras, int idproductos) {
       this.idcompras = idcompras;
       this.idproductos = idproductos;
    }
   
    public int getIdcompras() {
        return this.idcompras;
    }
    
    public void setIdcompras(int idcompras) {
        this.idcompras = idcompras;
    }
    public int getIdproductos() {
        return this.idproductos;
    }
    
    public void setIdproductos(int idproductos) {
        this.idproductos = idproductos;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TieneId) ) return false;
		 TieneId castOther = ( TieneId ) other; 
         
		 return (this.getIdcompras()==castOther.getIdcompras())
 && (this.getIdproductos()==castOther.getIdproductos());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdcompras();
         result = 37 * result + this.getIdproductos();
         return result;
   }   


}


