package Modelos;
// Generated 10-jun-2019 1:48:46 by Hibernate Tools 4.3.1



/**
 * Tiene generated by hbm2java
 */
public class Tiene  implements java.io.Serializable {


     private TieneId id;
     private Compras compras;
     private Productos productos;
     private int cantidad;

    public Tiene() {
    }

    public Tiene(TieneId id, Compras compras, Productos productos, int cantidad) {
       this.id = id;
       this.compras = compras;
       this.productos = productos;
       this.cantidad = cantidad;
    }
   
    public TieneId getId() {
        return this.id;
    }
    
    public void setId(TieneId id) {
        this.id = id;
    }
    public Compras getCompras() {
        return this.compras;
    }
    
    public void setCompras(Compras compras) {
        this.compras = compras;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


