package Modelos;
// Generated 10-jun-2019 1:48:46 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer idusuario;
     private String nombre;
     private String pass;
     private Date createTime;

     public Usuarios() {
    }

	
    public Usuarios( String nombre, String pass) {
        
        this.nombre = nombre;
        this.pass = pass;
    }
    public Usuarios(int idusuario, String nombre, String pass, Date createTime) {
       this.idusuario = idusuario;
       this.nombre = nombre;
       this.pass = pass;
       this.createTime = createTime;
    }
   
    public Integer getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }




}


