package Modelos;
// Generated 10-jun-2019 1:48:46 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ventas generated by hbm2java
 */
public class Ventas  implements java.io.Serializable {


     private Integer idventas;
     private Clientes clientes;
     private String referencia;
     private Long importe;
     private Date createTime;
     private Set contienes = new HashSet(0);

    public Ventas() {
    }

	
    public Ventas(Clientes clientes, String referencia,Long importe,Date createTime) {
        this.clientes = clientes;
        this.referencia = referencia;
        this.importe = importe;
        this.createTime = createTime;
    }
    public Ventas(Clientes clientes, String referencia, Long importe, Date createTime, Set contienes) {
       this.clientes = clientes;
       this.referencia = referencia;
       this.importe = importe;
       this.createTime = createTime;
       this.contienes = contienes;
    }
   
    public Integer getIdventas() {
        return this.idventas;
    }
    
    public void setIdventas(Integer idventas) {
        this.idventas = idventas;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public Long getImporte() {
        return this.importe;
    }
    
    public void setImporte(Long importe) {
        this.importe = importe;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Set getContienes() {
        return this.contienes;
    }
    
    public void setContienes(Set contienes) {
        this.contienes = contienes;
    }




}


